***  

# Welcome to P8400 - Principles of Epidemiology III

*** 

As part of my Master of Public Health (MPH) in Epidemiology program with the Mailman School of Public Health at Columbia University we were required to take a series of core epidemiology courses. In the Fall of 2019 I, and all other Epi students, took P8400 - Principles of Epidemiology III. The course was structured around a ~two hour lecture followed by a ~one hour lab. These labs are the basis for this project.

Most, if not all, schools of public health continue to teach using the industry-standard SAS. Unfortunately, this can be very limiting to those who might seek positions in organizations that are attempting to steer away from their dependence on SAS, or do not use it at all. As such, with this project I intend to go through my lab work again, though using only R.  

**Note**: None of the exercises discussed herein belong to me. I only have access to these materials because I was a matriculated student from September 2018 through May 2020. As such, this repository is not public and only available to those for whom I showed.  

***  