---
title: "Fall 2021 Course Schedule"
output: 
    html_document:
        toc: true
        toc_float: true
        toc_depth: 4
---  

***  

### 00. Pre-Course Assessment  

<span style="color: red;">**To be completed before class on Tuesday, September 3, 2021**</span>  

Online Assessment (Epi concept and SAS review - Available through Canvas)  

#### Learning Objectives  

* The first part will contain questions testing basic epidemiology concepts  
* The second part will contain questions testing basic SAS familiarity  
* Goal: to help instructors and TAs tailor the course and laboratory sessions to students’ level of comfort with pre-requisite material  
* You will be given 1 hour to complete the quiz which can be taken anytime within the provided 1 week time window  

<span style="color: red;">Pre-semester assessment to be taken on Canvas by Tuesday, September 3 at 10:00 a.m. (available on Canvas in the Quizzes tab by August 26)</span>  

***  

### 01. Causal Inference, Measures of Effect and Association, Multivariable Model  

**Tuesday, September 3, 2021**  

#### Learning Objectives  

* Discuss causal inference and the concept of the counterfactual
* Distinguish between absolute vs. relative measures of effect and association
* Explain the relationships among various measures of association
* Discuss the multivariable model and its advantages over tabular analyses for analysis
of epidemiologic data  

#### Lab 1  

* Let’s get reacquainted with SAS: review of Odss Ratios and Risk Ratios, and relationships between Odds Ratios, Incidence Rate Ratios, and Risk Ratios  

#### Reading  

* [Rothman KJ. J Gen Intern Med 2014;29(7):1060-1064.](documents/rothman.pdf)  

***  

### 02. Precision and Bias  

**Tuesday, September 10, 2021** 

#### Learning Objectives  

* Discuss and compare precision and bias  
* Explain how selection bias, information bias, and confounding can influence observed
measures of association  
* Discriminate between selection bias, information bias, and confounding  
* Distinguish between confounding and mediation  

#### Lab 2  

* Bias: assess confounding by stratified analysis  

#### Reading  

* [Nichol et al. NEJM 2007;357:1373-1381.](documents/nichol.pdf)  

***  

### 03. Interaction  

**Tuesday, September 17, 2021**

#### Learning Objectives  

* Describe and distinguish between statistical and biological interaction  
* Assess interaction on the additive and multiplicative scales  
* Explore interaction in stratified and regression analyses  

#### Lab 3  

* Interaction: evaluate additive and multiplicative interaction by stratified analysis  

#### Reading  

* [Flink et al. PLoS ONE. 2013;8(8):e70070](documents/flink.pdf)  

<span style="color: red;">**Homework 1 is Due**</span>  

***  

### 04. Case-Control Analysis I  

**Tuesday, September 24, 2021**

#### Learning Objectives  

* Summarize the design elements of a case-control study  
* Describe the measure of association used for a case-control study  
* Discuss the fundamental concepts underlying the logistic regression model and when it is useful for the analysis of epidemiologic data  
* Demonstrate approaches for deciding which covariates to include in a multivariable model  

#### Lab 4    

* Logistic Regression: assess confounding and interaction using regression  

#### Reading  

* [Hogervorst et al. JNCI 2009;101:651-662](documents/hogervorst.pdf)  

<span style="color: red;">**Homework 2 is Due**</span>  

***  

### 05. Case-Control Analysis II  

**Tuesday, October 1, 2021**

#### Learning Objectives  

* Demonstrate approaches to evaluate linearity
* Evaluate confounding and interaction using a multivariable model
* Describe model evaluation
* Discuss and apply an extension of the logistic model – Polytomous Regression

#### Lab 5  

* Model Building, Assessing Linearity, Polytomous Modeling  

#### Reading  

* [Merritt et al. British Journal of Cancer 2014; 110: 1392–1401](documents/merritt.pdf)  

<span style="color: red;">**Homework 3 is Due**</span>  

***  

### Review for Midterm

**Tuesday, October 8, 2021**

#### Lecture  

* Midterm review of concepts up through case-control analysis II  

#### Lab  

* We will review sample midterm questions in lab based on midterm review problem set  

<span style="color: red;">**Homework 4 is Due**</span>  

***  

### In-Class Midterm  

**Tuesday, October 15, 2021**

In-class midterm exam - 1:00 p.m. to 3:50 p.m.  

***  

### 06. Cohort/Follow-up Analysis & Age, Period, Cohort Effects  

**Tuesday, October 22, 2021**

#### Learning Objectives  

* Summarize the design elements of a cohort study
* Describe and discuss utility of analysis of age, period, and cohort effects
* Describe and demonstrate basic survival analysis: Life Table and Kaplan-Meier methods 

#### Lab 6  

* Kaplan Meier / Non-Parametric Survival Analysis  

#### Reading  

* [Bresalier et al. NEJM 2005;352(11):1092-1102](documents/bresalier.pdf)  
* [Keyes et al. IJE 2012;41:495–503](documents/keyes.pdf)  

***  

### 07. Cohort/Follow-up Analysis II  

**Tuesday, October 29, 2021**

#### Learning Objectives  

* Describe and discuss the choices for multivariable models of survival data once we move beyond Kaplan-Meier and Life Table methods
* Discuss the Cox Proportional Hazards Model and describe its assumptions
* Decide when the Cox model is a good choice for the analysis of epidemiologic data
* Demonstrate approaches for evaluating whether the assumptions of this model have been met
* Review an application of the Cox model from the literature
* Explain the concept of time-varying covariates
* Demonstrate the utility of time-varying covariates in the analysis of data from cohort studies
* Evaluate confounding and interaction using a multivariable model

#### Lab 7  

* Cox PH Modeling  

#### Reading  

* [Tobias et al. NEJM 2014;370:233-44](documents/tobias.pdf)  
* [Powell et al. 2012. (time varying covariates article)](documents/powell.pdf)  

***  

### No Class - Election Day  

**Tuesday, November 5, 2021**  

<span style="color: red;">Take-home quiz to be taken on Canvas by Tuesday, November 5th at 1:00 p.m.</span>  

***  

### 08. Matched Analysis and Correlated Data  

**Tuesday, November 12, 2021**  

#### Learning Objectives  

* Describe the purpose and benefits of matching in case-control  
* Summarize tabular analyses for matched data  
* Discuss regression models suitable for matched data; apply these methods  
* Discuss different options for handling correlated data  
* Compare and contrast GEE and MLMs  

#### Lab 8  

*  Matching and Modeling: Conditional Logistic Regression  

#### Reading  

* [Ludvigsson et al. JAMA Psychiatry. 2013;70(11):1224-1230](documents/ludvigsson.pdf)  
* [Shen et al. PLoS ONE 2012; 7(9):e44308](documents/shen.pdf)  

<span style="color: red;">**Homework 5 is Due**</span>  

***  

### 09. Poisson Regression and Advanced Topics  

**Tuesday, November 19, 2021**  

#### Learning Objectives  

* Describe and give examples of types of correlated data
* Examine commonly used regression models for correlated data
* Discuss poisson regression model and describe its assumptions
* Decide when the poisson model is a good choice for the analysis of epidemiologic data
* Demonstrate approaches for evaluating whether the assumptions of the Poisson model have been met
* Describe relative risk regression  

#### Lab 9  

* GEE, poisson and relative risk regression  

#### Reading  

* [Perkins et al. Cancer 2014;120:2514-21](documents/perkins.pdf)  
* [Fang et al. NEJM 2012;366:1310-8.](documents/fang.pdf)  

<span style="color: red;">**Take-home quiz to be taken on Canvas by Tuesday, November 19th at 1:00 p.m.**</span>  

***  

### 10. Synthesis of the Literature  

**Tuesday, November 26, 2021**  

#### Learning Objectives  

* Discuss and distinguish between narrative reviews, meta-analysis, and pooled analysis  
* Explain statistical methods used in meta- and pooled analyses  

#### Lab 10  

* Synthesis of Literature and Meta-Analysis  
* Discussion of Auvinen et al., Hepworth et al., and Lönn et al.  

#### Reading  

* [Auvinen, Anssi, et al. Epidemiology 13.3 (2002): 356-359.](documents/auvinen.pdf)  
* [Hepworth, Sarah J., et al. BMJ 332.7546 (2006): 883-887.](documents/hepworth.pdf)  
* [Lönn, Stefan, et al. Epidemiology 15.6 (2004): 653-659.](documents/lonn.pdf)  

<span style="color: red;">**Homework 6 due**</span>  

***  

### Review for Final Exam  

**Tuesday, December 3, 2021**  

Take-home portion of final exam available on Canvas by end of day on Tuesday, December 3   

***  

### In-Class Final Exam  

**Tuesday, December 10, 2021**  

In-class portion of final exam - 1:00 p.m. to 2:50 p.m.  

***  

### Take-Home Final Exam  

**Tuesday, December 12, 2021**  

Take-home portion of final exam due on Thursday, December 12 by 12:00 p.m.  

Final exams should be submitted **in-person**; submission details will be provided closer to exam date.  